- name: Deploy Flask App using Docker
  hosts: localhost
  become: true
  tasks:

    - name: Stop and remove any existing container named flask-app
      shell: |
        docker rm -f flask-app || true
      ignore_errors: yes

    - name: Run new Flask container
      shell: |
        docker run -d -p 5000:5000 --name flask-app flaskapp:latest
