---
- name: Deploy Flask App using Docker
  hosts: localhost
  become: true
  tasks:

    - name: Stop and remove any existing container
      shell: docker rm -f flask-app || true
      ignore_errors: true

    - name: Run new Flask container on port 5001
      shell: docker run -d -p 5001:5001 --name flask-app flaskapp:latest
