- name: Deploy Flask App using Docker
  hosts: localhost
  tasks:
    - name: Stop old container
      shell: docker stop flask-app || true && docker rm flask-app || true

    - name: Run new container
      shell: docker run -d -p 5000:5000 --name flask-app flaskapp:latest
